import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/shared/ui/Header";
import Footer from "@/shared/ui/Footer";
import Notification from "@/shared/ui/Notification";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bookstore - Luciana Bacci T",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const routes = [
    { name: "Inicio", path: "/" },
    { name: "Autores", path: "/authors" },
    { name: "Crear Autor", path: "/crear" },
    { name: "Libros", path: "/books"}
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col min-h-screen`}>
        <Notification />
        <Header routes={routes} />
        <div className="flex-grow">{children}</div>
        <Footer />
      </body>
    </html>
  );
}

