- name: Build & Push
  uses: docker/build-push-action@v5
  with:
    context: .
    file: ./Dockerfile
    push: true
    build-args: |
      NEXT_PUBLIC_DOCKER_API_URL=http://127.0.0.1:8080/api
    tags: |
      lbaccit/lbaccitbookstoreweb:latest
      lbaccit/lbaccitbookstoreweb:${{ github.sha }}
